Questions.jsx and Quotes.jsx mobile responsiveness
acm-ucr/robosub-website pull request #72
Opened 2024-01-24 03:19 UTC by swedenagu

<img width="406" alt="Screenshot 2024-01-23 at 7 16 44 PM" src="https://github.com/acm-ucr/robosub-website/assets/84001329/b815c359-647a-4a33-95c1-71b4c078ddd0">
<img width="408" alt="Screenshot 2024-01-23 at 7 17 19 PM" src="https://github.com/acm-ucr/robosub-website/assets/84001329/dc98e9e9-74e7-4cfb-9d7f-9b59c8b76572">
<img width="409" alt="Screenshot 2024-01-23 at 7 17 56 PM" src="https://github.com/acm-ucr/robosub-website/assets/84001329/91f5a69d-fe66-43a0-b2ca-2aea65b0e41f">

2024-01-25 01:11 UTC, ysh0305 requested changes
The website's original view is changed. You should not be changing the original formatting. You can put md: to keep the original setting on the laptop view and change only the mobile view.  The mobile still need to be improved

2024-01-26 02:58 UTC, swedenagu commented
> The website's original view is changed. You should not be changing the original formatting. You can put md: to keep the original setting on the laptop view and change only the mobile view. The mobile still need to be improved

<img width="1680" alt="Screenshot 2024-01-25 at 6 53 57 PM" src="https://github.com/acm-ucr/robosub-website/assets/84001329/f6f821b0-18ee-4de1-ac69-50c21c34ff42">
<img width="1680" alt="Screenshot 2024-01-25 at 6 55 10 PM" src="https://github.com/acm-ucr/robosub-website/assets/84001329/d48dce89-49cc-48fc-8ff7-f5d76a6ab290">
<img width="1680" alt="Screenshot 2024-01-25 at 6 55 38 PM" src="https://github.com/acm-ucr/robosub-website/assets/84001329/a5c846d3-fe74-40c1-b945-b11f5d2e99c3">
<img width="1680" alt="Screenshot 2024-01-25 at 6 55 55 PM" src="https://github.com/acm-ucr/robosub-website/assets/84001329/3314afb3-5a0e-44d0-a4fb-5a93e2dbdef5">

2024-01-28 08:30 UTC, ysh0305 requested changes
Overall, there are quite a few formatting on the laptop view that shouldn't be changed as you should only be changing the mobile view.  I think it is easier for you to discard your changes and restart the issues with a new branch (restart from step 1). If your local repo is not updated to the new dev branch on GitHub, you can reclone the repo and delete the old folder.

2024-01-28 08:30 UTC, ysh0305 commented on src/components/join/Questions.jsx
> +            className="w-2/3 md:max-w-full mr-[7%] text-xs pr-2 md:pr-8"
Formatting for the laptop view are changed

2024-01-28 08:30 UTC, ysh0305 commented on src/components/join/Quotes.jsx
> +    <div className="grid lg:grid-cols-2 mt-[3%] w-2/3 md:max-w-full text-xs">
Formatting for the laptop view are changed

2024-01-28 08:30 UTC, ysh0305 commented on src/components/join/Questions.jsx
> +            className=" border-l-robosub-blue text-sm lg:w-1/4 border-l-8 pl-[4%] md:pr-[0%] pr-[8%] font-bold "
Formatting for the laptop view are changed

2024-02-01 07:22 UTC, closed without merging